// AUTO-GENERATED by build.rs — do not edit by hand.
// Re-generated whenever ../../src or ../../dist changes.

/// Return `(content_type, bytes)` for a dist asset by its URL path,
/// or `None` if the path is not known.
pub fn get_asset(path: &str) -> Option<(&'static str, &'static [u8])> {
    match path {
        "/index.html" => Some(("text/html; charset=utf-8", include_bytes!("/Users/cphillipson/Development/active/ai/battleship/dist/index.html"))),
        "/scripts/webrtc.js" => Some(("application/javascript", include_bytes!("/Users/cphillipson/Development/active/ai/battleship/dist/scripts/webrtc.js"))),
        "/scripts/game.js" => Some(("application/javascript", include_bytes!("/Users/cphillipson/Development/active/ai/battleship/dist/scripts/game.js"))),
        "/scripts/renderer.js" => Some(("application/javascript", include_bytes!("/Users/cphillipson/Development/active/ai/battleship/dist/scripts/renderer.js"))),
        "/scripts/game-flow.js" => Some(("application/javascript", include_bytes!("/Users/cphillipson/Development/active/ai/battleship/dist/scripts/game-flow.js"))),
        "/scripts/styles.css" => Some(("text/css", include_bytes!("/Users/cphillipson/Development/active/ai/battleship/dist/scripts/styles.css"))),
        "/scripts/board.js" => Some(("application/javascript", include_bytes!("/Users/cphillipson/Development/active/ai/battleship/dist/scripts/board.js"))),
        "/scripts/landing.js" => Some(("application/javascript", include_bytes!("/Users/cphillipson/Development/active/ai/battleship/dist/scripts/landing.js"))),
        "/game.html" => Some(("text/html; charset=utf-8", include_bytes!("/Users/cphillipson/Development/active/ai/battleship/dist/game.html"))),
        _ => None,
    }
}
