// signal is exported from the lib crate so integration tests can reach it.
use cog_battleship::signal;

// assets.rs is generated by build.rs into OUT_DIR.
include!(concat!(env!("OUT_DIR"), "/assets.rs"));

use std::env;
use std::sync::Arc;

use serde_json::{json, Value};
use subtle::ConstantTimeEq;
use tiny_http::{Header, Method, Request, Response, Server, StatusCode};

use signal::RoomStore;

// ---------------------------------------------------------------------------
// Startup
// ---------------------------------------------------------------------------

fn main() {
    let token = env::var("COGNITUM_COG_TOKEN")
        .expect("COGNITUM_COG_TOKEN env var must be set");

    // Substitute the build-time placeholder with the real runtime token once at
    // startup so every HTML serve is a cheap clone, not a per-request allocation.
    let render_html = |asset_path: &str| -> Arc<Vec<u8>> {
        let bytes = get_asset(asset_path)
            .map(|(_, b)| b)
            .unwrap_or_default();
        let substituted = String::from_utf8_lossy(bytes)
            .replace("__COG_TOKEN__", &token)
            .into_bytes();
        Arc::new(substituted)
    };
    let index_html = render_html("/");
    let game_html  = render_html("/game");

    let store = Arc::new(RoomStore::new());

    let server = Server::http("127.0.0.1:8073")
        .expect("failed to bind 127.0.0.1:8073");

    eprintln!("cog-battleship listening on 127.0.0.1:8073");

    for request in server.incoming_requests() {
        let token      = token.clone();
        let store      = Arc::clone(&store);
        let index_html = Arc::clone(&index_html);
        let game_html  = Arc::clone(&game_html);
        std::thread::spawn(move || {
            handle(request, &token, &store, &index_html, &game_html);
        });
    }
}

// ---------------------------------------------------------------------------
// Router
// ---------------------------------------------------------------------------

fn handle(mut req: Request, token: &str, store: &Arc<RoomStore>, index_html: &[u8], game_html: &[u8]) {
    let method = req.method().clone();
    let url = req.url().to_owned();

    // Split path from query string
    let (path, query) = match url.find('?') {
        Some(i) => (&url[..i], &url[i + 1..]),
        None => (url.as_str(), ""),
    };

    // Open endpoints — no auth required
    match (&method, path) {
        (Method::Get, "/health") => {
            return json_response(req, 200, json!({"status": "ok"}));
        }
        (Method::Get, "/") => {
            return html_response(req, index_html);
        }
        (Method::Get, "/game") => {
            return html_response(req, game_html);
        }
        _ => {}
    }

    // Static assets: GET /scripts/{file}
    if method == Method::Get {
        if let Some(rest) = path.strip_prefix("/scripts/") {
            if !rest.contains("..") {
                let asset_key = format!("/scripts/{}", rest);
                return asset_response(req, &asset_key);
            }
        }
    }

    // ---------------------------------------------------------------------------
    // Paired endpoints — Bearer token auth required
    // ---------------------------------------------------------------------------

    if !check_auth(&req, token) {
        return json_response(req, 401, json!({"error": "unauthorized"}));
    }

    // POST /signal/create
    if method == Method::Post && path == "/signal/create" {
        let code = store.create_room();
        return json_response(req, 200, json!({"code": code}));
    }

    // Routes with a room code: /signal/{code}/...
    if let Some(rest) = path.strip_prefix("/signal/") {
        // rest is "{code}/{action}"
        let parts: Vec<&str> = rest.splitn(2, '/').collect();
        if parts.len() == 2 {
            let code = parts[0];
            let action = parts[1];

            match (&method, action) {
                // POST /signal/{code}/join
                (Method::Post, "join") => {
                    if store.join_room(code) {
                        return json_response(req, 200, json!({"ok": true}));
                    } else {
                        return json_response(
                            req,
                            404,
                            json!({"error": "room not found or closed"}),
                        );
                    }
                }

                // POST /signal/{code}/push
                (Method::Post, "push") => {
                    let payload = read_json_body(&mut req);
                    if store.push_message(code, payload) {
                        return json_response(req, 200, json!({"ok": true}));
                    } else {
                        return json_response(
                            req,
                            404,
                            json!({"error": "room not found or closed"}),
                        );
                    }
                }

                // GET /signal/{code}/poll?seq=N
                (Method::Get, "poll") => {
                    let from_seq = parse_seq(query);
                    match store.poll(code, from_seq, 20_000) {
                        Some(msgs) if msgs.is_empty() => {
                            // Timeout with no new messages — 204 No Content
                            return no_content(req);
                        }
                        Some(msgs) => {
                            let next_seq = msgs.last().map(|(s, _)| s + 1).unwrap_or(from_seq);
                            let arr: Vec<Value> = msgs
                                .into_iter()
                                .map(|(s, v)| json!({"seq": s, "payload": v}))
                                .collect();
                            return json_response(
                                req,
                                200,
                                json!({"messages": arr, "seq": next_seq}),
                            );
                        }
                        None => {
                            return json_response(
                                req,
                                404,
                                json!({"error": "room not found"}),
                            );
                        }
                    }
                }

                // POST /signal/{code}/leave
                (Method::Post, "leave") => {
                    store.leave_room(code);
                    return json_response(req, 200, json!({"ok": true}));
                }

                _ => {}
            }
        }
    }

    // 404 fallthrough
    json_response(req, 404, json!({"error": "not found"}));
}

// ---------------------------------------------------------------------------
// Auth
// ---------------------------------------------------------------------------

fn check_auth(req: &Request, token: &str) -> bool {
    for header in req.headers() {
        if header.field.as_str().as_bytes().eq_ignore_ascii_case(b"authorization") {
            let val = header.value.as_str();
            if let Some(bearer) = val.strip_prefix("Bearer ") {
                return bearer.as_bytes().ct_eq(token.as_bytes()).into();
            }
        }
    }
    false
}

// ---------------------------------------------------------------------------
// Response helpers
// ---------------------------------------------------------------------------

fn json_response(req: Request, status: u16, body: Value) {
    let body_str = body.to_string();
    let response = Response::from_string(body_str)
        .with_status_code(StatusCode(status))
        .with_header(
            Header::from_bytes(
                &b"Content-Type"[..],
                &b"application/json"[..],
            )
            .unwrap(),
        );
    let _ = req.respond(response);
}

fn html_response(req: Request, body: &[u8]) {
    let response = Response::from_data(body.to_vec())
        .with_status_code(StatusCode(200))
        .with_header(
            Header::from_bytes(&b"Content-Type"[..], &b"text/html; charset=utf-8"[..]).unwrap(),
        );
    let _ = req.respond(response);
}

fn no_content(req: Request) {
    let _ = req.respond(Response::empty(StatusCode(204)));
}

fn asset_response(req: Request, path: &str) {
    match get_asset(path) {
        Some((content_type, bytes)) => {
            let response = Response::from_data(bytes.to_vec())
                .with_status_code(StatusCode(200))
                .with_header(
                    Header::from_bytes(
                        &b"Content-Type"[..],
                        content_type.as_bytes(),
                    )
                    .unwrap(),
                );
            let _ = req.respond(response);
        }
        None => {
            json_response(req, 404, json!({"error": "asset not found"}));
        }
    }
}

// ---------------------------------------------------------------------------
// Body / query helpers
// ---------------------------------------------------------------------------

fn read_json_body(req: &mut Request) -> Value {
    let mut body = String::new();
    if req.as_reader().read_to_string(&mut body).is_ok() {
        serde_json::from_str(&body).unwrap_or(Value::Null)
    } else {
        Value::Null
    }
}

fn parse_seq(query: &str) -> u64 {
    for part in query.split('&') {
        if let Some(val) = part.strip_prefix("seq=") {
            if let Ok(n) = val.parse::<u64>() {
                return n;
            }
        }
    }
    0
}
