use std::fs;
use std::io::Write;
use std::path::Path;
use std::process::Command;

fn main() {
    let dist_path = Path::new("../../dist");
    let src_path = Path::new("../../src");

    // Tell cargo to rerun if src or dist changes
    println!("cargo:rerun-if-changed=../../src");
    println!("cargo:rerun-if-changed=../../dist");

    // Determine if we need to (re)build the frontend
    let needs_build = if !dist_path.exists() {
        true
    } else {
        // Compare modification times: if any src file is newer than dist, rebuild
        let dist_mtime = dir_mtime(dist_path);
        let src_mtime = dir_mtime(src_path);
        match (src_mtime, dist_mtime) {
            (Some(s), Some(d)) => s > d,
            _ => true,
        }
    };

    if needs_build {
        eprintln!("build.rs: running pnpm build ...");
        let status = Command::new("pnpm")
            .args(["build"])
            .current_dir("../../")
            // COG_MODE=true selects the cog variant of game.astro (webrtc-cog.js import,
            // cog-mode/cog-token meta tags). COG_TOKEN is set to the literal placeholder
            // string; main.rs substitutes the real runtime token at serve time.
            .env("COG_MODE", "true")
            .env("COG_TOKEN", "__COG_TOKEN__")
            .status()
            .expect("build.rs: failed to spawn pnpm build");
        if !status.success() {
            panic!("build.rs: pnpm build failed with status {}", status);
        }
    }

    // Generate src/assets.rs from dist/ contents
    generate_assets(dist_path);
}

/// Return the maximum mtime of any file inside `dir`.
fn dir_mtime(dir: &Path) -> Option<std::time::SystemTime> {
    let mut latest: Option<std::time::SystemTime> = None;
    if let Ok(entries) = walk_dir(dir) {
        for path in entries {
            if let Ok(meta) = fs::metadata(&path) {
                if let Ok(t) = meta.modified() {
                    latest = Some(match latest {
                        Some(prev) => prev.max(t),
                        None => t,
                    });
                }
            }
        }
    }
    latest
}

/// Recursively collect all file paths under `dir`.
fn walk_dir(dir: &Path) -> std::io::Result<Vec<std::path::PathBuf>> {
    let mut result = Vec::new();
    if dir.is_dir() {
        for entry in fs::read_dir(dir)? {
            let entry = entry?;
            let path = entry.path();
            if path.is_dir() {
                result.extend(walk_dir(&path)?);
            } else {
                result.push(path);
            }
        }
    }
    Ok(result)
}

/// Generate `$OUT_DIR/assets.rs` embedding all files in `dist/`.
fn generate_assets(dist_path: &Path) {
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set");
    let out_path = std::path::Path::new(&out_dir).join("assets.rs");
    let mut out = fs::File::create(&out_path)
        .expect("build.rs: cannot create assets.rs in OUT_DIR");

    writeln!(out, "// AUTO-GENERATED by build.rs — do not edit by hand.").unwrap();
    writeln!(out, "// Re-generated whenever ../../src or ../../dist changes.").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "/// Return `(content_type, bytes)` for a dist asset by its URL path,").unwrap();
    writeln!(out, "/// or `None` if the path is not known.").unwrap();
    writeln!(out, "pub fn get_asset(path: &str) -> Option<(&'static str, &'static [u8])> {{").unwrap();
    writeln!(out, "    match path {{").unwrap();

    if let Ok(files) = walk_dir(dist_path) {
        for file_path in &files {
            if !file_path.is_file() {
                continue;
            }

            // Build the URL key: strip the dist_path prefix, normalise to forward slashes
            let relative = file_path
                .strip_prefix(dist_path)
                .expect("build.rs: strip_prefix failed");
            let url_key = format!("/{}", relative.to_string_lossy().replace('\\', "/"));

            let mime = mime_for(file_path);

            // Use an absolute path so include_bytes! always resolves correctly
            let abs = file_path
                .canonicalize()
                .expect("build.rs: canonicalize failed");
            let abs_str = abs.to_string_lossy().replace('\\', "/");

            writeln!(
                out,
                "        {:?} => Some(({:?}, include_bytes!({:?}))),",
                url_key, mime, abs_str
            )
            .unwrap();
        }
    }

    writeln!(out, "        _ => None,").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();
}

/// Infer a MIME type from a file extension.
fn mime_for(path: &Path) -> &'static str {
    match path.extension().and_then(|e| e.to_str()) {
        Some("html") => "text/html; charset=utf-8",
        Some("js") | Some("mjs") => "application/javascript",
        Some("css") => "text/css",
        Some("json") => "application/json",
        Some("png") => "image/png",
        Some("svg") => "image/svg+xml",
        Some("ico") => "image/x-icon",
        Some("woff2") => "font/woff2",
        Some("woff") => "font/woff",
        _ => "application/octet-stream",
    }
}
